{
    'name': 'Quan ly cong viec',
    'version': '15.0.1.0.0',
    'summary': 'Quan ly cong viec gan voi khach hang',
    'description': 'Quan ly cong viec, tien trinh, dashboard, tu dong hoa va lien ket khach hang.',
    'category': 'Services',
    'author': 'BTL Nhom 1',
    'license': 'LGPL-3',
    'depends': ['quan_ly_nhan_su', 'quan_ly_khach_hang'],
    'data': [
        'security/ir.model.access.csv',
        'data/task_sequence.xml',
        'data/task_stage_data.xml',
        'data/task_dashboard_data.xml',
        'data/task_cron.xml',
        'views/task_views.xml',
        'views/task_stage_views.xml',
        'views/task_dashboard_views.xml',
        'views/task_reminder_views.xml',
        'views/customer_inherit_views.xml',
        'views/employee_inherit_views.xml',
        'views/task_menus.xml',
    ],
    'application': True,
    'installable': True,
}